customCommands:
- command: git cz c
  context: files
  description: commit with commitizen
  key: Z
  loadingText: opening commitizen commit tool
  output: terminal
- command: git commit --allow-empty -m 'empty commit'
  context: commits
  description: Add empty commit
  key: E
  loadingText: Committing empty commit...
disableStartupPopups: true
gui:
  authorColors:
    '*': '#b4befe'
  theme:
    activeBorderColor:
    - '#f5e0dc'
    - bold
    cherryPickedCommitBgColor:
    - '#45475a'
    cherryPickedCommitFgColor:
    - '#f5e0dc'
    defaultFgColor:
    - '#cdd6f4'
    inactiveBorderColor:
    - '#a6adc8'
    optionsTextColor:
    - '#89b4fa'
    searchingActiveBorderColor:
    - '#f9e2af'
    selectedLineBgColor:
    - '#313244'
    unstagedChangesColor:
    - '#f38ba8'
keybinding:
  commits:
    moveDownCommit: <c-n>
    moveUpCommit: <c-p>
