[[mgr.prepend_keymap]]
on = ["l"]
run = "plugin fast-enter"
desc = "Enter the subfolder faster, or open the file directly"
[[mgr.prepend_keymap]]
on = ["C"]
run = "plugin ouch"
desc = "Compress with ouch"
[[mgr.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"
[[mgr.prepend_keymap]]
on = "M"
run = "plugin mount"
[[mgr.prepend_keymap]]
on = "f"
run = "plugin jump-to-char"
desc = "Jump to char"
[[mgr.prepend_keymap]]
on = "e"
run = "shell --block -- nvim -c 'ContinueLoad'"
desc = "open cwd with neovim"
